export const RECONCILIATION_REASON_CODE = {
  LEGACY_PROVIDER_DISPATCH_UNKNOWN: "LEGACY_PROVIDER_DISPATCH_UNKNOWN",
  MULTIPLE_FROZEN_PAYMENT_ATTEMPTS: "MULTIPLE_FROZEN_PAYMENT_ATTEMPTS",
  FROZEN_PAYMENT_AUTHORITY_MISMATCH: "FROZEN_PAYMENT_AUTHORITY_MISMATCH",
  PROVIDER_REQUEST_AUTHORITY_MISMATCH: "PROVIDER_REQUEST_AUTHORITY_MISMATCH",
  PROVIDER_DISCOVERY_UNRESOLVED: "PROVIDER_DISCOVERY_UNRESOLVED",
  CHECKOUT_PAYMENT_ATTEMPT_MISMATCH: "CHECKOUT_PAYMENT_ATTEMPT_MISMATCH",
  ORDER_BIRTH_EXECUTION_AMBIGUOUS: "ORDER_BIRTH_EXECUTION_AMBIGUOUS",
  ORDER_RECOVERY_MULTIPLE_MATCHES: "ORDER_RECOVERY_MULTIPLE_MATCHES",
  ORDER_RECOVERY_INCOMPLETE: "ORDER_RECOVERY_INCOMPLETE",
  ORDER_BIRTH_AUTHORITY_CONFLICT: "ORDER_BIRTH_AUTHORITY_CONFLICT",
  ORDER_BIRTH_MARKER_CONFLICT: "ORDER_BIRTH_MARKER_CONFLICT",
  ORDER_BIRTH_MULTIPLE_ORDERS_FOUND: "ORDER_BIRTH_MULTIPLE_ORDERS_FOUND",
  ORDER_BIRTH_SCAN_INCOMPLETE: "ORDER_BIRTH_SCAN_INCOMPLETE",
  LATE_SUCCEEDED_AUTHORITY_CONFLICT: "LATE_SUCCEEDED_AUTHORITY_CONFLICT",
  RECONCILIATION_REQUIRED: "RECONCILIATION_REQUIRED",
} as const

export type ReconciliationReasonCode =
  (typeof RECONCILIATION_REASON_CODE)[keyof typeof RECONCILIATION_REASON_CODE]

export const RECONCILIATION_REASON_CODES = Object.values(
  RECONCILIATION_REASON_CODE
) as readonly ReconciliationReasonCode[]
